url: https://neryuuk.github.io

timezone: America/Sao_Paulo

# The base URL of your site
baseurl: "/"

pages:
  banana:
    layout: ats
    path: /ats

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"
