url: https://neryuuk.github.io
timezone: America/Sao_Paulo
baseurl: /
encoding: utf-8

defaults:
  -
    scope:
      path: pages/ats
      type: pages
    values:
      layout: ats
      permalink: /:basename

  -
    scope:
      path: pages/pretty
      type: pages
    values:
      layout: two-column
      permalink: /pretty/:basename

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"
