url: https://neryuuk.github.io
timezone: America/Sao_Paulo
baseurl: /
encoding: utf-8

compress_html:
  clippings: all
  endings: all
  startings: all

defaults:
  -
    scope:
      path: pages/pretty
      type: pages
    values:
      layout: two-column
      permalink: /:basename
  -
    scope:
      path: pages/ats
      type: pages
    values:
      layout: ats
      permalink: /cv/:basename

exclude:
  - "*.gem"
  - "*.gemspec"
  - pages/ats
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"
