url: https://neryuuk.github.io

timezone: America/Sao_Paulo

baseurl: /

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"
