name: Build & Deploy GitHub Pages

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with container
        run: |
          docker run \
            --volume ${{ github.workspace }}:/usr/src \
            ruby:3.3.7-alpine3.21 \
            /bin/sh -c "cd /usr/src && \
              apk add --update build-base && \
              gem update --system 3.6.3 && \
              gem install bundler --version 2.6.3 && \
              bundle install && \
              JEKYLL_ENV=production bundle exec jekyll build --future --safe --trace"
      - name: Configure Pages
        uses: actions/configure-pages@v5
        if: ${{ github.event_name == 'push' }}
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        if: ${{ github.event_name == 'push' }}
        with:
          path: ${{ github.workspace }}/_site
  Deploy:
    runs-on: ubuntu-24.04
    needs: Build
    if: ${{ github.event_name == 'push' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Pages
        uses: actions/deploy-pages@v4
        id: deployment
