name: Test Build Jekyll

on:
  pull_request:
    branches: ["main","master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Build with container
        run: |
          docker run \
            --env JEKYLL_ENV=production \
            --env JEKYLL_GID=`id --group` \
            --env JEKYLL_UID=`id --user` \
            --env JEKYLL_DEBUG=true \
            --env RUBY_DOWNLOAD_SHA256=d9cb65ecdf3f18669639f2638b63379ed6fbb17d93ae4e726d4eb2bf68a48370 \
            --env RUBY_MAJOR=3.2 \
            --env RUBY_VERSION=3.2.6 \
            --env VERBOSE=true \
            --volume ${{ github.workspace }}:/srv/jekyll \
            jekyll/builder:latest \
            /bin/bash -c "apk add ruby && ruby -v && bundle update --verbose && bundle exec jekyll build --future --profile --safe --trace --verbose"
