name: Build & Deploy GitHub Pages

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with container
        run: VOLUME=${{ github.workspace }} ./build.sh
      - name: Configure Pages
        uses: actions/configure-pages@v5
        if: ${{ github.event_name == 'push' }}
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        if: ${{ github.event_name == 'push' }}
        with:
          path: ${{ github.workspace }}/_site
  Deploy:
    runs-on: ubuntu-24.04
    needs: Build
    if: ${{ github.event_name == 'push' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Pages
        uses: actions/deploy-pages@v4
        id: deployment
