name: Deploy GitHub Pages

on:
  push:
    branches: ["main","master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Build with container
        run: |
          docker run \
            --volume ${{ github.workspace }}:/usr/src \
            ruby:3.3.7-alpine3.21 \
            /bin/sh -c "cd /usr/src && \
              apk add --update build-base && \
              bundle install && \
              JEKYLL_ENV=production bundle exec jekyll build --future --safe --trace"
      - uses: actions/configure-pages@v5
        name: Configure Pages
      - uses: actions/upload-pages-artifact@v3
        name: Upload Pages Artifact
        with:
          path: ${{ github.workspace }}/_site
  Deploy:
    runs-on: ubuntu-24.04
    needs: Build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        name: Deploy Pages
        id: deployment
