name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches: ["main","master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with jekyll/builder container
        run: |
          docker run \
            --env JEKYLL_ENV=production \
            --env JEKYLL_GID=${{ GROUPS }} \
            --env JEKYLL_UID=${{ UID }} \
            --volume ${{ github.workspace }}:/srv/jekyll \
            --volume ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:latest \
            /bin/bash -c "bundle update && bundle exec jekyll build --future --verbose"
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/_site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
