name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches: ["main","master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Build with container
        run: |
          docker run \
            --env JEKYLL_ENV=production \
            --env JEKYLL_GID=`id --group` \
            --env JEKYLL_UID=`id --user` \
            --volume ${{ github.workspace }}:/srv/jekyll \
            --volume ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:latest \
            /bin/bash -c "bundle update && bundle exec jekyll build --future --trace --verbose"
      - uses: actions/configure-pages@v5
        name: Configure Pages
      - uses: actions/upload-pages-artifact@v3
        name: Upload Pages Artifact
        with:
          path: ${{ github.workspace }}/_site
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        name: Deploy Pages
        id: deployment
